// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0

package database

import (
	"time"

	"github.com/google/uuid"
)

type Song struct {
	ID          string
	Name        string
	ArtistName  string
	AlbumName   string
	AlbumArt    string
	Duration    string
	VideoID     string
	IsAvailable bool
	ReleaseDate time.Time
	CreatedAt   time.Time
	UpdatedAt   time.Time
}

type SongFollow struct {
	ID        uuid.UUID
	SongID    string
	UserID    uuid.UUID
	CreatedAt time.Time
	UpdatedAt time.Time
}

type User struct {
	ID           uuid.UUID
	CreatedAt    time.Time
	UpdatedAt    time.Time
	Username     string
	Email        string
	Password     string
	RefreshToken string
}
