// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0
// source: song_follows.sql

package database

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const createSongFollow = `-- name: CreateSongFollow :one
INSERT INTO song_follows (id, song_id, user_id, created_at, updated_at)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, song_id, user_id, created_at, updated_at
`

type CreateSongFollowParams struct {
	ID        uuid.UUID
	SongID    string
	UserID    uuid.UUID
	CreatedAt time.Time
	UpdatedAt time.Time
}

func (q *Queries) CreateSongFollow(ctx context.Context, arg CreateSongFollowParams) (SongFollow, error) {
	row := q.db.QueryRowContext(ctx, createSongFollow,
		arg.ID,
		arg.SongID,
		arg.UserID,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	var i SongFollow
	err := row.Scan(
		&i.ID,
		&i.SongID,
		&i.UserID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
